<a href="https://colab.research.google.com/github/diazonic/pytorch/blob/master/PyTorch_Part_2_Tensors_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


For more info on the operations of Tensors


https://pytorch.org/docs/stable/tensors.html

# 1. Stride Operation

In [0]:
import torch
t0 = torch.randn(3,2)
t0

tensor([[-0.1868, -0.8337],
        [-0.0640,  0.1071],
        [-2.0111,  0.9209]])

In [0]:
t0.stride()
#https://stackoverflow.com/questions/56659255/what-does-layout-torch-strided-mean

(2, 1)

In [0]:
t1 = torch.as_strided(t0,(1,2),(4,2),1)
t1
#Taking value from index 1 and jumping 4 steps after it to take second value from index 5

tensor([[-0.8337,  0.1071]])

In [0]:
t2 = torch.as_strided(t0,(2,2),(3,2),0)
t2
# Taking the stride as (3,2) . It starts from 0th index which is 0.6163, then on index 1 we need to put the value by taking stride as 2 which gives the
# value at index 3 which is -0.3774. Next taking the stride value of 3 from index 1 which will be -.07161 forms the next number. Now from -0.7161 take, 2 values making
# 0.5596 as last number

tensor([[-0.1868, -0.0640],
        [ 0.1071,  0.9209]])

In [0]:
t3 = torch.as_strided(t0,(3,3),(1,2))
t3

RuntimeError: ignored

# **2.Quantized Tensor**

Scaling Tensors in the same way

In [0]:
torch.quantize_per_tensor(torch.tensor([-0.5, 0.5, 1.0, 2.0]), 0.2, 5, torch.quint8).int_repr()

tensor([ 2,  8, 10, 15], dtype=torch.uint8)

In [0]:
torch.quantize_per_tensor(torch.tensor([-5.0, 50.0, -10.0, 20.0]), 0.2, 5, torch.quint8).int_repr()

tensor([  0, 255,   0, 105], dtype=torch.uint8)

In [0]:
torch.quantize_per_tensor(torch.tensor([-15, 5, -10, 20]), 0.2, 100, torch.quint8).int_repr()

RuntimeError: ignored

# **3. Non Zero Index Tensor**

In [0]:
torch.nonzero(torch.tensor([1,2,3,0,6,0,9.8]))

tensor([[0],
        [1],
        [2],
        [4],
        [6]])

In [0]:
torch.nonzero(torch.tensor([[1,0,0,0],
                           [1,0,0,1]]))

/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)


tensor([[0, 0],
        [1, 0],
        [1, 3]])

In [0]:
torch.nonzero(torch.tensor([ord('A'),0,1]))

tensor([[0],
        [2]])

In [0]:
ord('A')

65

# **4. Condition on Tensor using where**

In [0]:
x = 12.5*torch.randn(4,5)
y = torch.zeros(1)
x

tensor([[ -3.9482,  -9.9197,   1.3945,  13.3218, -15.9004],
        [ -9.2214,  21.2780,  -0.4671,  -2.4064,   5.6129],
        [-14.5062,  26.1567,   4.9364,   5.1095,  10.4315],
        [ -3.5484,  22.1428,   0.9145,  -1.0481, -14.0949]])

In [0]:
torch.where(x>0,x,y)
# Accepting only positive value, negative values are replaced with zeros

tensor([[ 0.0000,  0.0000,  1.3945, 13.3218,  0.0000],
        [ 0.0000, 21.2780,  0.0000,  0.0000,  5.6129],
        [ 0.0000, 26.1567,  4.9364,  5.1095, 10.4315],
        [ 0.0000, 22.1428,  0.9145,  0.0000,  0.0000]])

In [0]:
torch.where(x>0,x,torch.round(x))
# All negative values to be rounded to nearest Integer

tensor([[ -4.0000, -10.0000,   1.3945,  13.3218, -16.0000],
        [ -9.0000,  21.2780,  -0.0000,  -2.0000,   5.6129],
        [-15.0000,  26.1567,   4.9364,   5.1095,  10.4315],
        [ -4.0000,  22.1428,   0.9145,  -1.0000, -14.0000]])

In [0]:
round(9.2)

9

In [0]:
torch.where((x>0.5) and (x <1.0),x,y)
# Complex equation cant be accepted

RuntimeError: ignored

# **5. Scatter method**

In [0]:
torch.zeros(3, 5).scatter_(0, torch.tensor([[0,1,1,1,1],[1,0,1,0,0]]), 14)


tensor([[14., 14.,  0., 14., 14.],
        [14., 14., 14., 14., 14.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [0]:
torch.zeros(2,2).scatter(1,torch.tensor([[1,0],[0,1]]),12)

tensor([[12., 12.],
        [12., 12.]])

In [0]:
torch.zeros(1,2).scatter(0,torch.tensor([[0,0]]),12)

tensor([[12., 12.]])